### ISSUE TITLE
Can't build on Debian Stretch, openssl 1.1.0c

### ISSUE THREAD

**Issue by RedChops** [NagiosEnterprises/nrpe#93]
Following the instructions on the in the PDF, ./configure works fine. Make, however, fails almost immediately with errors related to openssl 1.1:
```cd ./src/; make
make[1]: Entering directory '/home/dan/nrpe/src'
gcc -g -O2 -I/usr/include/openssl -DHAVE_CONFIG_H -I ../include -I ./../include -o nrpe ./nrpe.c ./utils.c ./acl.c -L/usr/lib/x86_64-linux-gnu  -lssl -lcrypto -lnsl
./nrpe.c: In function ‘init_ssl’:
./nrpe.c:264:33: warning: implicit declaration of function ‘RAND_status’ [-Wimplicit-function-declaration]
  if (allow_weak_random_seed && (RAND_status() == 0)) {
                                 ^~~~~~~~~~~
./nrpe.c:265:7: warning: implicit declaration of function ‘RAND_file_name’ [-Wimplicit-function-declaration]
   if (RAND_file_name(seedfile, sizeof(seedfile) - 1))
       ^~~~~~~~~~~~~~
./nrpe.c:266:8: warning: implicit declaration of function ‘RAND_load_file’ [-Wimplicit-function-declaration]
    if (RAND_load_file(seedfile, -1))
        ^~~~~~~~~~~~~~
./nrpe.c:267:5: warning: implicit declaration of function ‘RAND_write_file’ [-Wimplicit-function-declaration]
     RAND_write_file(seedfile);
     ^~~~~~~~~~~~~~~
./nrpe.c:277:5: warning: implicit declaration of function ‘RAND_seed’ [-Wimplicit-function-declaration]
     RAND_seed(seedfile, sizeof(seedfile));
     ^~~~~~~~~
./nrpe.c:283:10: warning: implicit declaration of function ‘SSLv2_server_method’ [-Wimplicit-function-declaration]
   meth = SSLv2_server_method();
          ^~~~~~~~~~~~~~~~~~~
./nrpe.c:283:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   meth = SSLv2_server_method();
        ^
./nrpe.c:290:3: warning: ‘TLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
   meth = TLSv1_server_method();
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../include/common.h:27,
                 from ./nrpe.c:28:
/usr/include/openssl/ssl.h:1597:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void)) /* TLSv1.0 */
                                             ^
./nrpe.c:293:3: warning: ‘TLSv1_1_server_method’ is deprecated [-Wdeprecated-declarations]
   meth = TLSv1_1_server_method();
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../include/common.h:27,
                 from ./nrpe.c:28:
/usr/include/openssl/ssl.h:1603:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void)) /* TLSv1.1 */
                                             ^
./nrpe.c:296:3: warning: ‘TLSv1_2_server_method’ is deprecated [-Wdeprecated-declarations]
   meth = TLSv1_2_server_method();
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../include/common.h:27,
                 from ./nrpe.c:28:
/usr/include/openssl/ssl.h:1609:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void)) /* TLSv1.2 */
                                             ^
./nrpe.c:317:16: warning: implicit declaration of function ‘ERR_get_error’ [-Wimplicit-function-declaration]
    while ((x = ERR_get_error()) != 0)
                ^~~~~~~~~~~~~
./nrpe.c:319:27: warning: implicit declaration of function ‘ERR_error_string’ [-Wimplicit-function-declaration]
         sslprm.cert_file, ERR_error_string(x, NULL));
                           ^~~~~~~~~~~~~~~~
./nrpe.c: In function ‘verify_callback’:
./nrpe.c:617:44: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
  X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), issuer, 256);
                                            ^~
./nrpe.c: In function ‘handle_conn_ssl’:
./nrpe.c:1752:16: warning: implicit declaration of function ‘ERR_get_error_line_data’ [-Wimplicit-function-declaration]
    while ((x = ERR_get_error_line_data(NULL, NULL, NULL, NULL)) != 0) {
                ^~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:1754:22: warning: implicit declaration of function ‘ERR_reason_error_string’ [-Wimplicit-function-declaration]
         remote_host, ERR_reason_error_string(x));
                      ^~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:1790:26: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
         remote_host, peer->valid ? "a " : "an in");
                          ^~
Makefile:48: recipe for target 'nrpe' failed
make[1]: *** [nrpe] Error 1
make[1]: Leaving directory '/home/dan/nrpe/src'
Makefile:66: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by box293** [comment]
Can you try the following guide and let us know if you come across the same problem:

https://support.nagios.com/kb/article.php?id=515

**Comment by RedChops** [comment]
Same issue, though more packages were installed:

```cd ./src/; make
make[1]: Entering directory '/home/dan/nrpe-3.0.1/src'
gcc -g -O2 -I/usr/include/openssl -DHAVE_CONFIG_H -I ../include -I ./../include -o nrpe ./nrpe.c ./utils.c ./acl.c -L/usr/lib/x86_64-linux-gnu  -lssl -lcrypto -lnsl
In file included from ./nrpe.c:35:0:
./../include/dh.h: In function ‘get_dh2048’:
./../include/dh.h:36:4: error: dereferencing pointer to incomplete type ‘DH {aka struct dh_st}’
  dh->p=BN_bin2bn(dh2048_p,sizeof(dh2048_p),NULL);
    ^~
./nrpe.c: In function ‘init_ssl’:
./nrpe.c:264:33: warning: implicit declaration of function ‘RAND_status’ [-Wimplicit-function-declaration]
  if (allow_weak_random_seed && (RAND_status() == 0)) {
                                 ^~~~~~~~~~~
./nrpe.c:265:7: warning: implicit declaration of function ‘RAND_file_name’ [-Wimplicit-function-declaration]
   if (RAND_file_name(seedfile, sizeof(seedfile) - 1))
       ^~~~~~~~~~~~~~
./nrpe.c:266:8: warning: implicit declaration of function ‘RAND_load_file’ [-Wimplicit-function-declaration]
    if (RAND_load_file(seedfile, -1))
        ^~~~~~~~~~~~~~
./nrpe.c:267:5: warning: implicit declaration of function ‘RAND_write_file’ [-Wimplicit-function-declaration]
     RAND_write_file(seedfile);
     ^~~~~~~~~~~~~~~
./nrpe.c:277:5: warning: implicit declaration of function ‘RAND_seed’ [-Wimplicit-function-declaration]
     RAND_seed(seedfile, sizeof(seedfile));
     ^~~~~~~~~
./nrpe.c:283:10: warning: implicit declaration of function ‘SSLv2_server_method’ [-Wimplicit-function-declaration]
   meth = SSLv2_server_method();
          ^~~~~~~~~~~~~~~~~~~
./nrpe.c:283:8: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   meth = SSLv2_server_method();
        ^
./nrpe.c:290:3: warning: ‘TLSv1_server_method’ is deprecated [-Wdeprecated-declarations]
   meth = TLSv1_server_method();
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../include/common.h:27,
                 from ./nrpe.c:28:
/usr/include/openssl/ssl.h:1597:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_server_method(void)) /* TLSv1.0 */
                                             ^
./nrpe.c:293:3: warning: ‘TLSv1_1_server_method’ is deprecated [-Wdeprecated-declarations]
   meth = TLSv1_1_server_method();
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../include/common.h:27,
                 from ./nrpe.c:28:
/usr/include/openssl/ssl.h:1603:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_server_method(void)) /* TLSv1.1 */
                                             ^
./nrpe.c:296:3: warning: ‘TLSv1_2_server_method’ is deprecated [-Wdeprecated-declarations]
   meth = TLSv1_2_server_method();
   ^~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ../include/common.h:27,
                 from ./nrpe.c:28:
/usr/include/openssl/ssl.h:1609:45: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_server_method(void)) /* TLSv1.2 */
                                             ^
./nrpe.c:317:16: warning: implicit declaration of function ‘ERR_get_error’ [-Wimplicit-function-declaration]
    while ((x = ERR_get_error()) != 0)
                ^~~~~~~~~~~~~
./nrpe.c:319:27: warning: implicit declaration of function ‘ERR_error_string’ [-Wimplicit-function-declaration]
         sslprm.cert_file, ERR_error_string(x, NULL));
                           ^~~~~~~~~~~~~~~~
./nrpe.c: In function ‘verify_callback’:
./nrpe.c:617:44: error: dereferencing pointer to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
  X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), issuer, 256);
                                            ^~
./nrpe.c: In function ‘handle_conn_ssl’:
./nrpe.c:1752:16: warning: implicit declaration of function ‘ERR_get_error_line_data’ [-Wimplicit-function-declaration]
    while ((x = ERR_get_error_line_data(NULL, NULL, NULL, NULL)) != 0) {
                ^~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:1754:22: warning: implicit declaration of function ‘ERR_reason_error_string’ [-Wimplicit-function-declaration]
         remote_host, ERR_reason_error_string(x));
                      ^~~~~~~~~~~~~~~~~~~~~~~
./nrpe.c:1790:26: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
         remote_host, peer->valid ? "a " : "an in");
                          ^~
Makefile:48: recipe for target 'nrpe' failed
make[1]: *** [nrpe] Error 1
make[1]: Leaving directory '/home/dan/nrpe-3.0.1/src'
Makefile:66: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by box293** [comment]
Thanks for trying. Sounds like it might be something with the newer version of openssl. I checked the previous version I tested that guide on and it was OpenSSL 0.9.8e.

One of the dev's will get back to you once they have a chance to look at it.

**Comment by smooge** [comment]
Running into this issue with trying to get Nagios updated in Fedora. The major problem looks to be with

./nrpe.c:1790:26: error: dereferencing pointer to incomplete type 'X509 {aka struct x509_st}'

with other errors related to this. The breakage seems to have affected a lot of packages in Debian/Fedora and SuSE so hopefully the fixes are easily standardized.

**Comment by smooge** [comment]
OK there are 2 issues. The first one I have a patch for below which uses options which openssl1 and openssl110 use. I don't know how far back they are so it might not be applicable to the main source code tree.

diff -up ./src/check_nrpe.c.opensslv110 ./src/check_nrpe.c
--- ./src/check_nrpe.c.opensslv110      2017-02-07 11:08:23.647733686 -0500
+++ ./src/check_nrpe.c  2017-02-07 12:44:22.314160593 -0500
@@ -980,9 +980,10 @@ int connect_to_remote()
                        if (peer) {
                                if (sslprm.log_opts & SSL_LogIfClientCert)
                                        syslog(LOG_NOTICE, "SSL %s has %s certificate",
-                                                  rem_host, peer->valid ? "a valid" : "an invalid");
+                                              rem_host, SSL_get_verify_result(ssl) ? "a valid" : "an invalid");
                                if (sslprm.log_opts & SSL_LogCertDetails) {
-                                       syslog(LOG_NOTICE, "SSL %s Cert Name: %s", rem_host, peer->name);
+                                       X509_NAME_oneline(X509_get_subject_name(peer), buffer, sizeof(buffer));
+                                       syslog(LOG_NOTICE, "SSL %s Cert Name: %s", rem_host, buffer);
                                        X509_NAME_oneline(X509_get_issuer_name(peer), buffer, sizeof(buffer));
                                        syslog(LOG_NOTICE, "SSL %s Cert Issuer: %s", rem_host, buffer);
                                }
@@ -1427,7 +1428,7 @@ int verify_callback(int preverify_ok, X5
        ssl = X509_STORE_CTX_get_ex_data(ctx, SSL_get_ex_data_X509_STORE_CTX_idx());
 
        X509_NAME_oneline(X509_get_subject_name(err_cert), name, 256);
-       X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), issuer, 256);
+       X509_NAME_oneline(X509_get_issuer_name(err_cert), issuer, 256);
 
        if (!preverify_ok && sslprm.client_certs >= Ask_For_Cert
                && (sslprm.log_opts & SSL_LogCertDetails)) {
diff -up ./src/nrpe.c.opensslv110 ./src/nrpe.c
--- ./src/nrpe.c.opensslv110    2016-09-08 12:18:58.000000000 -0400
+++ ./src/nrpe.c        2017-02-07 12:42:35.667799987 -0500
@@ -614,7 +614,7 @@ int verify_callback(int preverify_ok, X5
        ssl = X509_STORE_CTX_get_ex_data(ctx, SSL_get_ex_data_X509_STORE_CTX_idx());
 
        X509_NAME_oneline(X509_get_subject_name(err_cert), name, 256);
-       X509_NAME_oneline(X509_get_issuer_name(ctx->current_cert), issuer, 256);
+       X509_NAME_oneline(err_cert, issuer, 256);
 
        if (!preverify_ok && (sslprm.log_opts & SSL_LogCertDetails)) {
                syslog(LOG_ERR, "SSL Client has an invalid certificate: %s (issuer=%s) err=%d:%s",
@@ -1785,12 +1785,14 @@ int handle_conn_ssl(int sock, void *ssl_
                peer = SSL_get_peer_certificate(ssl);
 
                if (peer) {
+
                        if (sslprm.log_opts & SSL_LogIfClientCert)
                                syslog(LOG_NOTICE, "SSL Client %s has %svalid certificate",
-                                          remote_host, peer->valid ? "a " : "an in");
+                                      remote_host, SSL_get_verify_result(ssl) ? "a " : "an in");
                        if (sslprm.log_opts & SSL_LogCertDetails) {
+                               X509_NAME_oneline(X509_get_subject_name(peer), buffer, sizeof(buffer));
                                syslog(LOG_NOTICE, "SSL Client %s Cert Name: %s",
-                                          remote_host, peer->name);
+                                          remote_host, buffer);
                                X509_NAME_oneline(X509_get_issuer_name(peer), buffer, sizeof(buffer));
                                syslog(LOG_NOTICE, "SSL Client %s Cert Issuer: %s",
                                           remote_host, buffer);

**Comment by smooge** [comment]
The second issue is with the fact that the newer SSL does not have sslv2 and while you can define a -DOPENSSL_NO_SSL2 there are parts in the code which still references SSL2. I think it needs a bigger work and not sure what would fit the code plans.

**Comment by jfrickson** [comment]
Thanks for the patch. I'll be looking into all the sslv1x issues soon.

**Comment by jfrickson** [comment]
@RedChops @smooge 
A fix is in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/2a6486eafbdc2c688ca46713cce93a3e6fe568ca. Please test and see if this solves all the problems.

**Comment by mbrinkmann** [comment]
I did built it, but my plugins didn't work. reverted to the old jessie-binary and it works again.

**Comment by jfrickson** [comment]
Ok, I'll keep working on it. Thanks for the feedback.

**Comment by jfrickson** [comment]
@mbrinkmann I have a Jessie VM with OpenSSL 1.0.1t and nrpe 1.1.0 compiles fine. I could not find an OpenSSL 1.1 package. Did you build OpenSSL from scratch, or where did you get it?

**Comment by sebastic** [comment]
OpenSSL 1.1.0 is only in Debian stretch (testing) and unstable.

**Comment by jfrickson** [comment]
Ok, pulled it from testing. The only problem I had was
```
../include/dh.h:46: undefined reference to `DH_set0_pqg'
```
A short-term fix is to edit `configure` and at line 7283, set `need_dh=no` or at line 310 in `configure.ac`.

I'll add a configure flag to turn it off.

**Comment by jfrickson** [comment]
Should be fixed in branch `maint` via commit https://github.com/NagiosEnterprises/nrpe/commit/e0d5e50f95bfd91f4cc38b2ce839d48531a0cbd0

Use `./configure --with-need-dh=no` to exclude DH logic and not generate the key.

Post a comment here if there are still problems. Otherwise, will be included in version 3.1.1.
